added parameter for record-screen scirpt

diff --git a/bin/record-screen b/bin/record-screen
--- a/bin/record-screen
+++ b/bin/record-screen
@@ -1,9 +1,52 @@
 #!/bin/sh
 
-if [ -z "$1" ]; then 
+function print_usage () {
+
+			echo "Script for starting ffmpeg with options for optimized screen recording"
+			echo "If there are no arguments, script will be executed with default options"
+			echo -e "-o \t define output file"
+			echo -e "-r \t define screen resolution in format"
+
+}
+
+OUTPUT=""
+RESOLUTION=""
+
+while getopts :ho:r: OPTION; do
+	case $OPTION in 
+		h)
+			print_usage
+			exit 0
+			;;
+		o)
+			echo "output file"
+			OUTPUT="$OPTARG"
+			echo $o
+			;;
+		r)
+			RESOLUTION="$OPTARG"
+			echo "resolution"
+			echo $r
+			;;
+		
+		*)
+			echo "Invalid option"
+			print_usage
+			exit 1
+			;;
+
+	esac
+done
+
+
+if [[ -z $OUTPUT ]]; then
 	OUTPUT=output.mp4
-else
-	OUTPUT="$1"
 fi
 
-ffmpeg -video_size 1920x1080 -framerate 5 -f x11grab -i :0.0+0.0 -c:v libx264rgb -crf 0 -preset ultrafast -color_range 2 "$OUTPUT"
+if [[ -z $RESOLUTION ]]; then
+	RESOLUTION=$( xrandr | grep '*' | cut -f 4 -d ' ' )
+fi
+
+ffmpeg -video_size "$RESOLUTION" -framerate 5 -f x11grab -i :0.0+0.0 -c:v libx264rgb -crf 0 -preset ultrafast -color_range 2 "$OUTPUT"
+
+exit 0
